### ISSUE TITLE
增加和的专属AI

### ISSUE THREAD

**Issue by rolevax** [rolevax/libsaki#13]
重写`think`方法，跳过针对丰音和初美的部分，后面都一样

提交方式：

- 见[改代码前必读](https://mjpancake.github.io/docs/workflow/)
- 有任何问题，在[Gitter](https://gitter.im/mjpancake/Lobby?source=orgpage)提问。

验收通过条件：

- 功能正确，无明显bug，代码整洁并符合规范

**Comment by DeranW** [comment]
我在ai.cpp的147~167行找到了antiHatsumi和antiToyone的代码
是不是Nodoka用的直接是公共ai啊
所以是不是要新建一个Nodoka的ai然后把这两部分删掉
或者是在这两个的if语句里面做修改啊
