### ISSUE TITLE
测试老板娘三狗战表现

### ISSUE THREAD

**Issue by rolevax** [rolevax/libsaki#17]
任务目标：

- 参照[改代码前必读](https://mjpancake.github.io/docs/workflow)，下载`mjpancake`代码，确保本地的`mjpancake`与`libsaki`都在`new/sumire`分支上
- 编译并运行项目，以“堇+三京狗”的阵容打三个半庄，自己操作堇
- 打法：
    - 全程门前清，不鸣任何牌，可暗杠
    - 全程不立直
    - 若能力可发动，立即发动，狙击目标随意
- 统计堇的以下指标：
    - 发动能力次数
    - 发动能力后，成功以目标牌和牌次数
    - 记录每次发动能力后狙击失败的原因

提交内容：

- 统计结果
- 能证明统计结果的对应松饼牌谱文件 （`.pai.json` 格式）

牌谱文件在哪儿：

- Windows: C:/Users/用户名/AppData/Local/mjpancake/replay
- Linux: ~/.config/mjpancake/replay
- macOS: ~/Library/Preferences/mjpancake/replay

提交方式：

- 本issue下回复统计结果，以及牌谱文件的下载链接

验收通过条件：

- 打法符合上述要求，统计无误

**Comment by satsuki8** [comment]
半庄1（10：29）
东1.0 射击下家 成功
东3.0 射击下家 失败 自摸和牌 原因：下家被瞄准后未摸到铳牌（可能和下家做七对有关）
南3.0 射击下家 失败 自摸和牌 原因：瞄准后一巡自摸
半庄2（10：43）
南1.1 射击上家 失败 下家铳和 原因：上家在他家立直后防守
半庄3（11：35）
东3.0 射击上家 失败 下家铳和 原因：上家留住了孤张的铳牌（可能为保留牌型变化）
南1.1 射击下家 成功

发动能力6次，成功2次。

[replay.zip](https://github.com/rolevax/libsaki/files/1434381/replay.zip)

门清先制听牌困难，面对三京狗一局也只能发动两至三次能力，与原作半决赛中多次在六巡七巡听牌不符；射击失败率高；未发现能力描述中任意次数射击的功能。
