### ISSUE TITLE
测试结衣三狗战表现

### ISSUE THREAD

**Issue by rolevax** [rolevax/libsaki#23]
任务目标：

- 参照[改代码前必读](https://mjpancake.github.io/docs/workflow)，下载`mjpancake`代码，确保本地的`mjpancake`与`libsaki`都在最新的`develop`分支上
- 编译并运行项目，以“结衣+三京狗”的阵容打三个半庄，自己操作结衣
- 打法：
    - 该日日，该弃弃，不好判断的情况随意
    - 进攻时不鸣牌，不暗杠
    - 进攻时“在不倒退向听数的前提下”保持尽可能多的对子
- 统计结衣的以下指标：
    - 总和牌次数，七对和牌次数，四面和牌次数，自摸和牌次数
    - 详细记录每次四面子和牌时手牌里的对子个数

提交内容：

- 统计结果
- 能证明统计结果的对应松饼牌谱文件 （`.pai.json` 格式）

牌谱文件在哪儿：

- Windows: C:/Users/用户名/AppData/Local/mjpancake/replay
- Linux: ~/.config/mjpancake/replay
- macOS: ~/Library/Preferences/mjpancake/replay

提交方式：

- 本issue下回复统计结果以及牌谱文件

验收通过条件：

- 打法符合上述要求，统计无误

**Comment by satsuki8** [comment]
[replay.zip](https://github.com/rolevax/libsaki/files/1466654/replay.zip)

半庄1 （18:18）
东3.3 四面荣和 3个对子（其中1个有三张）
东4.0 四面荣和 4个对子（其中3个有三张）
南2.0 四面自摸 3个对子（其中2个有三张）
南2.1 四面自摸 5个对子（其中2个有三张）

半庄2（18:40）
东2.0 四面荣和 3个对子

半庄3（18:53）
东2.0 四面自摸 4个对子
东3.0 四面荣和 2个对子（其中2个有三张）

三个半庄，总和牌次数7次，七对和牌0次（有七对听牌），四面和牌7次，自摸和牌3次。

**Comment by satsuki8** [comment]
[replay.zip](https://github.com/rolevax/libsaki/files/1487659/replay.zip)

半庄1 （20:14）
东2.2 七对自摸
东2.3 四面荣和，6个对子（击飞结束）

半庄2 （20:27）
东1.0 四面荣和，2个对子（为保持一向听拆过两次对子）
东2.0 七对荣和
东3.0 七对荣和
南3.1 四面自摸，4个对子（击飞结束）

半庄3 （20:42）
南1.0 七对荣和
南2.0 四面荣和，4个对子
南4.0 七对自摸

三个半庄，总和牌次数9次，七对和牌5次，四面和牌4次，自摸和牌3次。
