### ISSUE TITLE
三狗战统计系列之瓦卡奶

### ISSUE THREAD

**Issue by rolevax** [rolevax/libsaki#25]
任务目标：

- 参照[改代码前必读](https://mjpancake.github.io/docs/workflow)，下载`mjpancake`代码，确保本地的`mjpancake`与`libsaki`都在最新的`develop`分支上
- 编译并运行项目，以“三寻木+三京狗”的阵容打三个半庄，自己操作三寻木
- 使用慕篇规则（无一发、无赤、无里、无杠宝牌）
- 打法：
    - 进攻时保持门前清
    - 从配牌开始只考虑跳满或以上的牌
    - 听牌后如果立直也不够跳满食和，则拆听
    - 听牌后如果立直后刚好够跳满食和，则立直
    - 默听食和已跳满或以上的，不立直
- 记录每一次和牌的以下指标：
    - 翻数及手役咒语串
    - 和了巡目
    - 自摸还是食和

提交内容：

- 统计结果
- 能证明统计结果的对应松饼牌谱文件 （`.pai.json` 格式）

牌谱文件在哪儿：

- Windows: C:/Users/用户名/AppData/Local/mjpancake/replay
- Linux: ~/.config/mjpancake/replay
- macOS: ~/Library/Preferences/mjpancake/replay

提交方式：

- 本issue下回复统计结果以及牌谱文件

验收通过条件：

- 打法符合上述要求，统计无误

**Comment by satsuki8** [comment]
[replay.zip](https://github.com/rolevax/libsaki/files/1490648/replay.zip)
半庄1 （16:23）
东2.0 8番（七对子门清），9巡食和

半庄2 （16:52）
东4.1 12番（自摸三暗刻门清dora3），12巡自摸
南1.2 7番（立断平自摸三色dora1），12巡自摸

半庄3 （16:57）
东2.0 7番（立平自摸三色dora2），15巡自摸
东2.1 6番（门清nomi），14巡食和

**Comment by satsuki8** [comment]
[replay.zip](https://github.com/rolevax/libsaki/files/1495648/replay.zip)
半庄1 （18:25）
东1.0 7番（自摸门清），13巡自摸
东2.0 7番（自摸门清），11巡自摸
东3.0 6番（门清nomi），8巡食和（击飞）

半庄2 （18:48）
东1.0 7番（自摸三色全带dora2），9巡自摸
东3.0 7番（立平自摸三色dora2）,14巡自摸
东3.1 7番（断平自摸三色dora2），12巡自摸（击飞）

半庄3 （18:55）
东1.1 9番（自摸一杯口三色纯全dora2），9巡自摸
东3.0 11番（三暗刻门清dora3），8巡食和（击飞）
